#!/usr/bin/env python3
"""export_ortler_loft.py — bake the real 80x80 Ortler hex grid into a loft data module.

Reads data/ortler_hexes.npz (the @PLN1 fixture: real EU-DEM heights + real OSM landcover,
80x80 odd-r hexes on the moros 1500 m convention) and writes src/ortlerdata.loft: the raw
height / OSM-class / river arrays as numeric-literal accessor functions, row-major
(idx = r*COLS + c). Numeric literals parse in ~0.2 s (verified), so the data compiles in —
no runtime file I/O. The OSM->K_ kind mapping + the model elevation classifier live in
src/ortlergen.loft (loft logic), not here; this is pure data.

Run from the repo root:  python3 plans/1-ortler-worldgen-fixture/export_ortler_loft.py
"""
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
NPZ = HERE / "data" / "ortler_hexes.npz"
OUT = REPO / "src" / "ortlerdata.loft"

d = np.load(NPZ)
h = d["h"]                     # (rows, cols) int16, metres
osm = d["osm"]                 # (rows, cols) int16, 0..10
river = d["river_mask"].astype(np.int16)   # (rows, cols) bool -> 0/1
rows, cols = int(d["rows"]), int(d["cols"])
hc, hr = int(d["hc"]), int(d["hr"])         # home cell (summit) = grid centre
assert h.shape == (rows, cols), h.shape


def arr_fn(name, a):
    flat = a.reshape(-1).tolist()           # row-major: idx = r*cols + c
    body = ",".join(str(int(v)) for v in flat)
    return f"pub fn {name}() -> vector<integer> {{ [{body}] }}\n"


lines = [
    "// ortlerdata — GENERATED by plans/1-ortler-worldgen-fixture/export_ortler_loft.py.\n",
    "// The real 80x80 Ortler hex grid (@PLN1): EU-DEM heights (m) + OSM landcover (0..10) +\n",
    "// river mask, row-major (idx = r*ORT_COLS + c). Same moros odd-r 1500 m convention as the\n",
    "// engine's overworld tier, so overworld_center / chunk_mesh_ov position it directly.\n",
    "// Do NOT hand-edit — re-run the exporter. Kind mapping: src/ortlergen.loft.\n",
    f"pub const ORT_COLS = {cols};\n",
    f"pub const ORT_ROWS = {rows};\n",
    f"pub const ORT_HC = {hc};   // home cell (Ortler summit) = grid centre col\n",
    f"pub const ORT_HR = {hr};   // home cell row\n",
    arr_fn("ort_h", h),
    arr_fn("ort_osm", osm),
    arr_fn("ort_river", river),
]
OUT.write_text("".join(lines))
kb = OUT.stat().st_size / 1024
print(f"wrote {OUT.relative_to(REPO)}  ({kb:.1f} KB)  {cols}x{rows}  "
      f"h={int(h.min())}..{int(h.max())} m  home=({hc},{hr})")
