#!/usr/bin/env python3
"""P4 blueprint — the R6 directed light cone + vignette (PLAN-RENDER P4).

Computes the post shader's EXACT formula (same constants as view.loft's
POSTFRAG) and prints the expected probe values for a uniform mid-gray (128)
scene — the table that seeds probes/post_r6.probe. Re-run after retuning the
constants to regenerate the expectations.

Screen: 800x600, anchor = the player (400, 420 in PNG top-left coords =
GL y 180 from bottom). Forward = screen UP (the egocentric view keeps the
facing up, so the cone is FIXED in screen space — no heading uniform).
"""
import math

W, H = 800.0, 600.0
AX, AY_GL = 400.0, 180.0      # anchor, GL coords (y up)
R_BEHIND, R_AHEAD = 240.0, 520.0
FLOOR = 0.35                   # light never goes fully dark inside the scene
VIG = 0.22                     # vignette strength at the exact corner
GRAY = 128.0

def factor(px_png, py_png):
    x, y = px_png + 0.5, (H - py_png) - 0.5          # pixel center, GL y-up
    dx, dy = x - AX, y - AY_GL
    dist = math.hypot(dx, dy)
    fwd = dy / dist if dist > 0 else 0.0
    rad = R_BEHIND + (R_AHEAD - R_BEHIND) * (fwd * 0.5 + 0.5)
    t = dist / rad
    light = max(FLOOR, 1.0 - t * t)
    u, v = x / W, y / H
    cx, cy = (u - 0.5) * 2.0, (v - 0.5) * 2.0
    vig = 1.0 - VIG * (math.hypot(cx, cy) / math.sqrt(2.0)) ** 3.0
    return light * max(0.0, vig)

def expect(name, x, y):
    v = round(GRAY * factor(x, y))
    print(f"probe {name} {x} {y} {v} {v} {v} tol 3")

print("# generated by tools/blueprints/light_cone.py — gray-128 scene expectations")
expect("anchor", 400, 420)
expect("ahead150", 400, 270)
expect("behind150", 400, 570)
expect("corner", 40, 40)
print("# forward>backward at equal distance:", round(GRAY*factor(400,270)), ">", round(GRAY*factor(400,570)))
print("# ramp ahead: mono dec",
      [round(GRAY*factor(400, y)) for y in range(420, 60, -60)])
