#!/usr/bin/env python3
"""Scan bundles/*/bundle.json and (re)generate the loft registries that wire them in.

Every system is cut up into bundles. A bundle's "kind" decides which registry it feeds; the
scanner dispatches by kind so the game never references a bundle directly — drop a dir, re-run
(make bundles), and it is wired. See BUNDLE.md.

    kind "character" -> src/bundles.loft   (bundle_activate / bundle_keys / bundle_name)
    kind "world"     -> src/rooms_gen.loft  (the rooms section: RoomDef table + how rooms connect)

A world bundle is a linkable PLACE that can hold several sections (rooms now; monster spawns,
terrain, level features later) — each section feeds its own registry. Another world bundle may
later carry a spawn rule that links to one of these places by key.

    python3 tools/gen_bundles.py
"""
import json, os, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load_bundles():
    out = []
    for mf in sorted(glob.glob(os.path.join(ROOT, "bundles", "*", "bundle.json"))):
        with open(mf) as f:
            out.append(json.load(f))
    return out


def gen_characters(chars):
    """kind:character -> src/bundles.loft (the load-script dispatch)."""
    L = [
        "// GENERATED by tools/gen_bundles.py — DO NOT EDIT BY HAND.",
        "// Pointers to the kind:\"character\" bundles discovered under bundles/*/bundle.json. Loose",
        "// coupling: drop a bundle dir, run `make bundles`, and it is wired here. See BUNDLE.md.",
        "use sim;",
        "use player;",
    ]
    for b in chars:
        L.append(f"use {b['module']};")
    L += [
        "",
        "// Activate a character bundle by key for the active player — runs its load-script.",
        "pub fn bundle_activate(s: &Sim, key: text) {",
        "  p = player_new(0);",
    ]
    for b in chars:
        L.append(f'  if key == "{b["key"]}" {{ {b["module"]}::{b["entry"]}(s, p); }}')
    L += [
        "}",
        "",
        "// The keys of every available character bundle (for a class-select screen, later).",
        "pub fn bundle_keys() -> vector<text> {",
        "  [" + ", ".join(f'"{b["key"]}"' for b in chars) + "]",
        "}",
        "",
        "pub fn bundle_name(key: text) -> text {",
    ]
    for b in chars:
        L.append(f'  if key == "{b["key"]}" {{ return "{b["name"]}"; }}')
    L += ['  ""', "}"]
    out = os.path.join(ROOT, "src", "bundles.loft")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    return len(chars)


def gen_world(world_bundles):
    """kind:world -- the rooms section -> src/rooms_gen.loft (room registry + connection model)."""
    rooms = []
    connect = {"mode": "corridors", "graph": "chain", "extra_loops": 0}
    depth = {"start": 1, "max": 50}
    for b in world_bundles:
        sec = b.get("rooms", {})
        connect = sec.get("connect", connect)
        rooms.extend(sec.get("list", []))
        depth = b.get("depth", depth)
    L = [
        "// GENERATED by tools/gen_bundles.py — DO NOT EDIT BY HAND.",
        "// Room registry from the rooms section of the kind:\"world\" bundles (bundles/*/bundle.json)",
        "// — the default room set and the way corridors connect them. Consumed by gen.loft. See BUNDLE.md.",
        "pub struct RoomDef {",
        "  rk: text, shape: text,",
        "  w_min: integer not null, w_max: integer not null,",
        "  h_min: integer not null, h_max: integer not null,",
        "  weight: integer not null,",
        "}",
        "",
        "pub fn room_table() -> vector<RoomDef> {",
        "  t: vector<RoomDef> = [];",
    ]
    for r in rooms:
        L.append(
            f'  t += [RoomDef {{ rk: "{r["key"]}", shape: "{r["shape"]}", '
            f'w_min: {r["w_min"]}, w_max: {r["w_max"]}, '
            f'h_min: {r["h_min"]}, h_max: {r["h_max"]}, weight: {r["weight"]} }}];'
        )
    L += [
        "  t",
        "}",
        "",
        "// How rooms connect to each other (the corridor model).",
        f'pub fn room_connect_mode() -> text {{ "{connect.get("mode", "corridors")}" }}',
        f'pub fn room_connect_graph() -> text {{ "{connect.get("graph", "chain")}" }}',
        f'pub fn room_connect_loops() -> integer {{ {int(connect.get("extra_loops", 0))} }}',
        "",
        "// The dungeon depth range this place provides; start = the default (shallowest) entry,",
        "// max = deepest. The actual entry depth is a parameter, so a more dangerous top area",
        "// can link in and start deeper (any level in [start, max]).",
        f'pub fn world_depth_start() -> integer {{ {int(depth.get("start", 1))} }}',
        f'pub fn world_depth_max() -> integer {{ {int(depth.get("max", 50))} }}',
    ]
    out = os.path.join(ROOT, "src", "rooms_gen.loft")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    return len(rooms)


def gen_world_defs(world_bundles):
    """kind:world enemy/item def MODULES -> src/bundle_defs.loft (the catalog-merge aggregator).

    Each world bundle may declare `"enemies": "<module>"` / `"items": "<module>"` pointing at a
    bundle-side .loft module exporting `enemies()` / `items()`. The content lives in the bundle; this
    emits one `use` + concat per module so catalog.loft can fold them into the game tables. No engine
    catalog (monsters.loft/items.loft) is touched — that is what keeps a bundle shareable.
    """
    enemy_mods = [b["enemies"] for b in world_bundles if b.get("enemies")]
    item_mods = [b["items"] for b in world_bundles if b.get("items")]
    L = [
        "// GENERATED by tools/gen_bundles.py — DO NOT EDIT BY HAND.",
        "// Aggregates the definition sections (enemies()/items()) of the kind:\"world\" bundles so the",
        "// catalog merge (catalog.loft) can fold them into the game tables. The content lives in the",
        "// bundle (bundles/<name>/...); this is just one `use` + concat per module. See BUNDLE.md.",
        "use monsters;",
        "use items;",
    ]
    for m in dict.fromkeys(enemy_mods + item_mods):  # dedup, keep order
        L.append(f"use {m};")
    L += ["", "pub fn bundle_monsters() -> vector<MonsterDef> {", "  t: vector<MonsterDef> = [];"]
    for m in enemy_mods:
        L += [
            f"  s_{m} = {m}::monster_defs();",
            f"  for i in 0..len(s_{m}) {{ if i < len(s_{m}) {{ t += [s_{m}[i]]; }} }}",
        ]
    L += ["  t", "}", "", "pub fn bundle_items() -> vector<ItemDef> {", "  t: vector<ItemDef> = [];"]
    for m in item_mods:
        L += [
            f"  s_{m} = {m}::item_defs();",
            f"  for i in 0..len(s_{m}) {{ if i < len(s_{m}) {{ t += [s_{m}[i]]; }} }}",
        ]
    L += ["  t", "}"]
    out = os.path.join(ROOT, "src", "bundle_defs.loft")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    return len(enemy_mods), len(item_mods)


def gen_world_place(world_bundles):
    """kind:world stencil/placement MODULES -> src/world_place_gen.loft.

    Forwards each world bundle's `"stencils": "<module>"` (a `stencils()` export) and its single
    `"placement": "<module>"` (a `placement()` export) so the engine placer (sim.loft) can stamp the
    set-piece + run the infestation/quest rules. Content + decisions live in the bundle; the engine
    only executes. With no placement bundle present, emits the empty-but-valid shape.
    """
    stencil_mods = [b["stencils"] for b in world_bundles if b.get("stencils")]
    place_mods = [b["placement"] for b in world_bundles if b.get("placement")]
    L = [
        "// GENERATED by tools/gen_bundles.py — DO NOT EDIT BY HAND.",
        "// Forwards the stencils()/placement() of the kind:\"world\" bundles to the engine placer",
        "// (sim.loft). The room templates + placement rules live in the bundle; see BUNDLE.md.",
        "use worldtypes;",
    ]
    for m in dict.fromkeys(stencil_mods + place_mods):
        L.append(f"use {m};")
    L += ["", "pub fn world_stencils() -> vector<Stencil> {", "  t: vector<Stencil> = [];"]
    for m in stencil_mods:
        L += [
            f"  s_{m} = {m}::room_stencils();",
            f"  for i in 0..len(s_{m}) {{ if i < len(s_{m}) {{ t += [s_{m}[i]]; }} }}",
        ]
    L += ["  t", "}", ""]
    if place_mods:
        # one quest overlay for now: forward the first bundle that declares placement
        L += [
            "pub fn world_has_placement() -> integer { 1 }",
            f"pub fn world_placement() -> Placement {{ {place_mods[0]}::place_rules() }}",
        ]
    else:
        L += [
            "pub fn world_has_placement() -> integer { 0 }",
            'pub fn world_placement() -> Placement {',
            '  Placement { setpiece_stencil: "", setpiece_depth: 0, boss_drop: "", quest_item: "", quest_depth: 0,',
            '    infest_trigger: "", infest_a: "", infest_b: "", infest_d1: 0, infest_d2: 0 }',
            "}",
        ]
    out = os.path.join(ROOT, "src", "world_place_gen.loft")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    return len(stencil_mods), len(place_mods)


def gen_race_defs(race_bundles):
    """kind:race -> src/race_defs_gen.loft (the race catalog-merge aggregator).

    One bundle = one race: each kind:"race" bundle declares `"race": "<module>"` pointing at a
    bundle-side .loft module exporting `race_defs()`. This emits one `use` + concat per module so
    catalog.loft (race_catalog) can fold them into the playable-race roster. No engine source
    (races.loft) is touched -- that, plus one-race-per-bundle, lets a modder ship a limited game by
    including only the race folders they want. Always emits a valid (possibly empty) shape.
    """
    race_mods = [b["race"] for b in race_bundles if b.get("race")]
    L = [
        "// GENERATED by tools/gen_bundles.py -- DO NOT EDIT BY HAND.",
        '// Aggregates the race_defs() of the kind:"race" bundles (one race per bundle) so the catalog',
        "// merge (catalog.loft) can fold them into race_catalog(). Content lives in bundles/<race>/;",
        "// this is just one `use` + concat per module. See BUNDLE.md.",
        "use races;",
    ]
    for m in dict.fromkeys(race_mods):
        L.append(f"use {m};")
    L += ["", "pub fn bundle_races() -> vector<RaceDef> {", "  t: vector<RaceDef> = [];"]
    for m in race_mods:
        # def fn is uniquely named <module>_race_defs() — same fn name across modules collides as a
        # duplicate global symbol on the NATIVE/WASM backend (E0428), even though interpret tolerates it.
        L += [
            f"  s_{m} = {m}::{m}_race_defs();",
            f"  for i in 0..len(s_{m}) {{ if i < len(s_{m}) {{ t += [s_{m}[i]]; }} }}",
        ]
    L += ["  t", "}"]
    out = os.path.join(ROOT, "src", "race_defs_gen.loft")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    return len(race_mods)


def main():
    bundles = load_bundles()
    chars = [b for b in bundles if b.get("kind") == "character"]
    world_bundles = [b for b in bundles if b.get("kind") == "world"]
    race_bundles = [b for b in bundles if b.get("kind") == "race"]
    nc = gen_characters(chars)
    nr = gen_world(world_bundles)
    ne, ni = gen_world_defs(world_bundles)
    ns, npl = gen_world_place(world_bundles)
    nra = gen_race_defs(race_bundles)
    print(
        f"gen_bundles: {nc} character bundle(s) -> src/bundles.loft "
        f"({', '.join(b['key'] for b in chars)}); "
        f"{nr} room type(s) -> src/rooms_gen.loft; "
        f"{ne} enemy + {ni} item def module(s) -> src/bundle_defs.loft; "
        f"{ns} stencil + {npl} placement module(s) -> src/world_place_gen.loft; "
        f"{nra} race bundle(s) -> src/race_defs_gen.loft"
    )


if __name__ == "__main__":
    main()
