#!/usr/bin/env python3
"""Scan bundles/*/bundle.json and (re)generate src/bundles.loft — the loosely-coupled index
that points to every discovered character bundle's loading module.

Loose coupling: nothing in the game references a bundle directly. Drop a new dir under
bundles/ with its <key>.loft load-script + bundle.json manifest, re-run this (make bundles),
and it is wired — the generated index `use`s the module and dispatches to it. See BUNDLE.md.

    python3 tools/gen_bundles.py        # -> src/bundles.loft
"""
import json, os, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

bundles = []
for mf in sorted(glob.glob(os.path.join(ROOT, "bundles", "*", "bundle.json"))):
    with open(mf) as f:
        bundles.append(json.load(f))

L = [
    "// GENERATED by tools/gen_bundles.py — DO NOT EDIT BY HAND.",
    "// Pointers to the character bundles discovered under bundles/*/bundle.json. Loose",
    "// coupling: drop a bundle dir, run `make bundles`, and it is wired here. See BUNDLE.md.",
    "use sim;",
    "use player;",
]
for b in bundles:
    L.append(f"use {b['module']};")
L += [
    "",
    "// Activate a character bundle by key for the active player — runs its load-script.",
    "pub fn bundle_activate(s: &Sim, key: text) {",
    "  p = player_new(0);",
]
for b in bundles:
    L.append(f'  if key == "{b["key"]}" {{ {b["module"]}::{b["entry"]}(s, p); }}')
L += [
    "}",
    "",
    "// The keys of every available bundle (for a class-select screen, later).",
    "pub fn bundle_keys() -> vector<text> {",
    "  [" + ", ".join(f'"{b["key"]}"' for b in bundles) + "]",
    "}",
    "",
    "pub fn bundle_name(key: text) -> text {",
]
for b in bundles:
    L.append(f'  if key == "{b["key"]}" {{ return "{b["name"]}"; }}')
L += ['  ""', "}"]

out = os.path.join(ROOT, "src", "bundles.loft")
with open(out, "w") as f:
    f.write("\n".join(L) + "\n")
print(f"gen_bundles: {len(bundles)} bundle(s) -> src/bundles.loft  ({', '.join(b['key'] for b in bundles)})")
