#!/usr/bin/env bash
# The headless deterministic test gate (extracted from the Makefile `test` target;
# `make test` delegates here). Same steps, same labels, same /tmp/story_*.log
# files — one table row per test, specials (kernel self-test, compile gate,
# bundle regeneration, the seam grep) written out where they sit in the order.
#
# Args: $1 = loft binary   $2 = loft flags (word-split: --path/--lib …)
#       $3 = kernel selftest .loft   $4 = game entry .loft
set -u
trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; printf '%s' "${s%"${s##*[![:space:]]}"}"; }
LOFT="$(trim "${1:?loft binary required}")"
FLAGS="${2-}"
KTEST="$(trim "${3:?kernel selftest .loft required}")"
SRC="$(trim "${4:?game entry .loft required}")"

# run <src-file> <ok-marker> <log> <fail-text> <label>
run() {
  echo "  $5"
  # shellcheck disable=SC2086  # FLAGS must word-split into --path/--lib
  "$LOFT" --interpret $FLAGS "$1" | tee "$3"
  grep -q "$2" "$3" || { echo "    FAIL: $4"; exit 1; }
}

# table <<EOF — file|marker|log|fail-text|label  (order = execution order)
table() {
  while IFS='|' read -r file marker log fail label; do
    [ -n "$file" ] || continue
    run "$file" "$marker" "$log" "$fail" "$label"
  done
}

echo "  [1/13] kernel self-test (headless, deterministic) ..."
# shellcheck disable=SC2086
"$LOFT" --interpret $FLAGS "$KTEST" | tee /tmp/story_selftest.log
grep -q "ALL CHECKS PASS" /tmp/story_selftest.log || {
  echo "    FAIL: kernel self-test did not pass"; exit 1; }

table <<'EOF'
src/combattest.loft|COMBAT OK|/tmp/story_combat.log|combat loop|[2/13] combat loop (player melee + enemy attacks) ...
src/wiretest.loft|WIRING OK|/tmp/story_wire.log|dungeon wiring|[3/13] dungeon wiring (procedural gen + DB monsters) ...
src/aitest.loft|AI OK|/tmp/story_ai.log|monster AI|[4/13] monster AI (awareness + never-move) ...
src/placetest.loft|PLACEMENT OK|/tmp/story_place.log|placement|[5/13] placement (budget + weighted + start-safe) ...
src/leveltest.loft|LEVEL OK|/tmp/story_level.log|levels|[6/13] levels (stairs + descent) ...
src/herotest.loft|HERO OK|/tmp/story_hero.log|hero|[7/13] hero (XP + level-up) ...
src/curvetest.loft|CURVE OK|/tmp/story_curve.log|curve|[8/13] curve + ratio cap (gentle, fair, capped) ...
src/itemtest.loft|ITEM OK|/tmp/story_item.log|items|[9/13] items (gold + drops + pickup) ...
src/equiptest.loft|EQUIP OK|/tmp/story_equip.log|equipment|[10/13] equipment (wield + effects) ...
src/savetest.loft|SAVE OK|/tmp/story_save.log|save points|[11/13] save points (checkpoint respawn + grave) ...
src/fovtest.loft|FOV OK|/tmp/story_fov.log|FOV|[12/13] FOV (facing-cone fog-of-war) ...
EOF

echo "  [13/13] compile gate (parse + bytecode) ..."
# shellcheck disable=SC2086
"$LOFT" --interpret --check $FLAGS "$SRC" >/dev/null 2>&1 || {
  echo "    FAIL: compile"; exit 1; }

echo "  [bundles] regenerate index + character-bundle test ..."
python3 tools/gen_bundles.py >/dev/null
run src/bundletest.loft "BUNDLE OK" /tmp/story_bundle.log "bundles" \
  "[bundles] character-bundle test ..."

table <<'EOF'
src/bundledeftest.loft|BUNDLEDEF OK|/tmp/story_bundledef.log|bundle-defs|[bundle-defs] world bundle enemies/items -> catalog merge ...
src/deftest.loft|DEFS OK|/tmp/story_defs.log|defs|[defs] class/race/item tables — races now per-bundle via race_catalog ...
src/roomtest.loft|ROOMS OK|/tmp/story_rooms.log|rooms|[rooms] rooms bundle -> room registry ...
src/itemusetest.loft|ITEM-USE OK|/tmp/story_itemuse.log|item-use|[items] item-use (Explorer potions: heal + custom detect) ...
src/clocktest.loft|CLOCK OK|/tmp/story_clock.log|clock|[clock] monster energy/speed (1.0x vs 1.5x) ...
src/statustest.loft|STATUS OK|/tmp/story_status.log|status|[status] timed statuses (slow / stun, pre-calc expiry) ...
src/persisttest.loft|PERSIST OK|/tmp/story_persist.log|persist|[persist] dungeon delta round-trip (death-only; regenerate + replay) ...
src/surfacetest.loft|SURFACE OK|/tmp/story_surface.log|surface|[surface] depth-0 desert + dungeon entrance (SLICE step 1+2) ...
src/skilltest.loft|SKILL OK|/tmp/story_skill.log|skill|[skills] passive melee skill (level + STR -> damage) ...
src/depthtest.loft|DEPTH OK|/tmp/story_depth.log|depth|[depth] beginner-dungeon spawn pool is depth-gentle (no lich at 1-3) ...
src/rangedtest.loft|RANGED OK|/tmp/story_ranged.log|ranged|[ranged] launcher fire action (bow + ammo -> shoot) ...
src/quickslottest.loft|QUICKSLOT OK|/tmp/story_quickslot.log|quickslot|[quickslot] type-routed auto-slot + bind + press-to-use dispatch ...
src/questtest.loft|QUEST OK|/tmp/story_quest.log|quest|[quest] desert_surprise overlay: throne set-piece + grant + boss -> infestation ...
src/msgtest.loft|MSG OK|/tmp/story_msg.log|msg|[msg] message log: ring buffer + event lines (kill/level/descend/nothing) ...
src/invhubtest.loft|INVHUB OK|/tmp/story_invhub.log|invhub|[invhub] inventory hub: two ring slots + equipped names + reslot bind ...
src/effecttest.loft|EFFECT OK|/tmp/story_effect.log|effect|[effect] use-item effects: blink / heal / restore / magic-mapping ...
src/specialtest.loft|SPECIAL OK|/tmp/story_special.log|special|[special] monster specials: gaze paralysis + venom + antivenin ward (+ deadlock/struggle) ...
src/unknowntest.loft|UNKNOWN OK|/tmp/story_unknown.log|unknown|[unknown] unknown items: per-game flavours / identify-on-use / carry / IF_KNOWN exempt ...
src/racetest.loft|RACE OK|/tmp/story_race.log|race|[race] chosen race applies: stat block / hit-die HP / skills / save / free-action gate ...
src/classtest.loft|CLASS OK|/tmp/story_class.log|class|[class] classes from bundles: apply / SP pool / the spell chain (routine-by-id) ...
src/crystaltest.loft|CRYSTAL OK|/tmp/story_crystal.log|crystal|[crystal] the shrine re-spec: bump = interact / apply race+class / roster ...
src/overlandtest.loft|OVERLAND OK|/tmp/story_overland.log|overland|[overland] the contract wilderness: invariants / walked scale / towns+roads ...
src/cavetest.loft|CAVE OK|/tmp/story_cave.log|cave|[cave] natural caves: mouths on the surface, narrow winding levels ...
EOF

echo "  [seam] trait seam: no engine spawn by monster key (PLAN-BUNDLES A) ..."
if grep -n 'mon_find("' src/*.loft | grep -v spawn_crystal | grep -q .; then
  echo "    FAIL: engine references a monster key:"
  grep -n 'mon_find("' src/*.loft | grep -v spawn_crystal
  exit 1
fi

table <<'EOF'
src/traveltest.loft|TRAVEL OK|/tmp/story_travel.log|travel|[travel] window crossing + the desert gate ...
src/idletest.loft|IDLESKIP OK|/tmp/story_idle.log|idle-skip|[idle-skip] scene key: hold when idle, bump on events (PLAN-RENDER P1) ...
EOF

# The games kernel (@PLN18 engine_host) lives in the sibling loft checkout — its
# natives ride the installed binary, the lib surface rides ../loft/lib. Skip (not
# fail) where the sibling is absent: the kernel dep is opt-in until registry-published.
if [ -d ../loft/lib/engine_host ]; then
  echo "  [kernel] engine_host consumable: natives + schema table (PLAN-KERNEL K0) ..."
  # shellcheck disable=SC2086
  "$LOFT" --interpret $FLAGS --lib ../loft/lib/ src/kerneltest.loft | tee /tmp/story_kernel.log
  grep -q "KERNEL OK" /tmp/story_kernel.log || { echo "    FAIL: kernel"; exit 1; }
else
  echo "  [kernel] SKIP — ../loft/lib not present (sibling-checkout dep, PLAN-KERNEL.md)"
fi

echo "  PASS"
