#!/usr/bin/env bash
# The headless deterministic test gate (extracted from the Makefile `test` target;
# `make test` delegates here). Same steps, same labels, same /tmp/story_*.log
# files — one table row per test, specials (kernel self-test, compile gate,
# bundle regeneration, the seam grep) written out where they sit in the order.
#
# Args: $1 = loft binary   $2 = loft flags (word-split: --path/--lib …)
#       $3 = kernel selftest .loft   $4 = game entry .loft
set -u
trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; printf '%s' "${s%"${s##*[![:space:]]}"}"; }
LOFT="$(trim "${1:?loft binary required}")"
FLAGS="${2-}"
KTEST="$(trim "${3:?kernel selftest .loft required}")"
SRC="$(trim "${4:?game entry .loft required}")"

# run <src-file> <ok-marker> <log> <fail-text> <label>
run() {
  echo "  $5"
  # shellcheck disable=SC2086  # FLAGS must word-split into --path/--lib
  "$LOFT" --interpret $FLAGS "$1" | tee "$3"
  grep -q "$2" "$3" || { echo "    FAIL: $4"; exit 1; }
}

# table <<EOF — file|marker|log|fail-text|label  (order = execution order)
table() {
  while IFS='|' read -r file marker log fail label; do
    [ -n "$file" ] || continue
    run "$file" "$marker" "$log" "$fail" "$label"
  done
}

echo "  [1/14] kernel self-test (headless, deterministic) ..."
# shellcheck disable=SC2086
"$LOFT" --interpret $FLAGS "$KTEST" | tee /tmp/story_selftest.log
grep -q "ALL CHECKS PASS" /tmp/story_selftest.log || {
  echo "    FAIL: kernel self-test did not pass"; exit 1; }

table <<'EOF'
src/combattest.loft|COMBAT OK|/tmp/story_combat.log|combat loop|[2/14] combat loop (player melee + enemy attacks) ...
src/wiretest.loft|WIRING OK|/tmp/story_wire.log|dungeon wiring|[3/14] dungeon wiring (procedural gen + DB monsters) ...
src/aitest.loft|AI OK|/tmp/story_ai.log|monster AI|[4/14] monster AI (awareness + never-move) ...
src/placetest.loft|PLACEMENT OK|/tmp/story_place.log|placement|[5/14] placement (budget + weighted + start-safe) ...
src/leveltest.loft|LEVEL OK|/tmp/story_level.log|levels|[6/14] levels (stairs + descent) ...
src/herotest.loft|HERO OK|/tmp/story_hero.log|hero|[7/14] hero (XP + level-up) ...
src/curvetest.loft|CURVE OK|/tmp/story_curve.log|curve|[8/14] curve + ratio cap (gentle, fair, capped) ...
src/itemtest.loft|ITEM OK|/tmp/story_item.log|items|[9/14] items (gold + drops + pickup) ...
src/equiptest.loft|EQUIP OK|/tmp/story_equip.log|equipment|[10/14] equipment (wield + effects) ...
src/savetest.loft|SAVE OK|/tmp/story_save.log|save points|[11/14] save points (checkpoint respawn + grave) ...
src/fovtest.loft|FOV OK|/tmp/story_fov.log|FOV|[12/14] FOV (facing-cone fog-of-war) ...
src/sprite_drawtest.loft|SPRITE OK|/tmp/story_sprite.log|sprite rasterizer|[13/14] sprite rasterizer (fill_polygon scanline) ...
EOF

echo "  [14/14] compile gate (parse + bytecode) ..."
# shellcheck disable=SC2086
"$LOFT" --interpret --check $FLAGS "$SRC" >/dev/null 2>&1 || {
  echo "    FAIL: compile"; exit 1; }

echo "  [bundles] regenerate index + character-bundle test ..."
"$LOFT" --interpret src/genbundles.loft >/dev/null 2>&1
run src/bundletest.loft "BUNDLE OK" /tmp/story_bundle.log "bundles" \
  "[bundles] character-bundle test ..."

table <<'EOF'
src/bundledeftest.loft|BUNDLEDEF OK|/tmp/story_bundledef.log|bundle-defs|[bundle-defs] world bundle enemies/items -> catalog merge ...
src/deftest.loft|DEFS OK|/tmp/story_defs.log|defs|[defs] class/race/item tables — races now per-bundle via race_catalog ...
src/roomtest.loft|ROOMS OK|/tmp/story_rooms.log|rooms|[rooms] rooms bundle -> room registry ...
src/itemusetest.loft|ITEM-USE OK|/tmp/story_itemuse.log|item-use|[items] item-use (Explorer potions: heal + custom detect) ...
src/clocktest.loft|CLOCK OK|/tmp/story_clock.log|clock|[clock] monster energy/speed (1.0x vs 1.5x) ...
src/statustest.loft|STATUS OK|/tmp/story_status.log|status|[status] timed statuses (slow / stun, pre-calc expiry) ...
src/persisttest.loft|PERSIST OK|/tmp/story_persist.log|persist|[persist] dungeon delta round-trip (death-only; regenerate + replay) ...
src/surfacetest.loft|SURFACE OK|/tmp/story_surface.log|surface|[surface] depth-0 desert + dungeon entrance (SLICE step 1+2) ...
src/skilltest.loft|SKILL OK|/tmp/story_skill.log|skill|[skills] passive melee skill (level + STR -> damage) ...
src/depthtest.loft|DEPTH OK|/tmp/story_depth.log|depth|[depth] beginner-dungeon spawn pool is depth-gentle (no lich at 1-3) ...
src/rangedtest.loft|RANGED OK|/tmp/story_ranged.log|ranged|[ranged] launcher fire action (bow + ammo -> shoot) ...
src/quickslottest.loft|QUICKSLOT OK|/tmp/story_quickslot.log|quickslot|[quickslot] type-routed auto-slot + bind + press-to-use dispatch ...
src/questtest.loft|QUEST OK|/tmp/story_quest.log|quest|[quest] desert_surprise overlay: throne set-piece + grant + boss -> infestation ...
src/msgtest.loft|MSG OK|/tmp/story_msg.log|msg|[msg] message log: ring buffer + event lines (kill/level/descend/nothing) ...
src/invhubtest.loft|INVHUB OK|/tmp/story_invhub.log|invhub|[invhub] inventory hub: two ring slots + equipped names + reslot bind ...
src/effecttest.loft|EFFECT OK|/tmp/story_effect.log|effect|[effect] use-item effects: blink / heal / restore / magic-mapping ...
src/specialtest.loft|SPECIAL OK|/tmp/story_special.log|special|[special] monster specials: gaze paralysis + venom + antivenin ward (+ deadlock/struggle) ...
src/unknowntest.loft|UNKNOWN OK|/tmp/story_unknown.log|unknown|[unknown] unknown items: per-game flavours / identify-on-use / carry / IF_KNOWN exempt ...
src/racetest.loft|RACE OK|/tmp/story_race.log|race|[race] chosen race applies: stat block / hit-die HP / skills / save / free-action gate ...
src/classtest.loft|CLASS OK|/tmp/story_class.log|class|[class] classes from bundles: apply / SP pool / the spell chain (routine-by-id) ...
src/crystaltest.loft|CRYSTAL OK|/tmp/story_crystal.log|crystal|[crystal] the shrine re-spec: bump = interact / apply race+class / roster ...
src/overlandtest.loft|OVERLAND OK|/tmp/story_overland.log|overland|[overland] the contract wilderness: invariants / walked scale / towns+roads ...
src/cavetest.loft|CAVE OK|/tmp/story_cave.log|cave|[cave] natural caves: mouths on the surface, narrow winding levels ...
EOF

echo "  [seam] trait seam: no engine spawn by monster key (plan #4 A) ..."
if grep -n 'mon_find("' src/*.loft | grep -v spawn_crystal | grep -q .; then
  echo "    FAIL: engine references a monster key:"
  grep -n 'mon_find("' src/*.loft | grep -v spawn_crystal
  exit 1
fi

table <<'EOF'
src/traveltest.loft|TRAVEL OK|/tmp/story_travel.log|travel|[travel] window crossing + the desert gate ...
src/idletest.loft|IDLESKIP OK|/tmp/story_idle.log|idle-skip|[idle-skip] scene key: hold when idle, bump on events (plan #7 P1) ...
src/pointstest.loft|POINTS OK|/tmp/story_points.log|railway-points|[points] turnout + reverse curve: 15-deg sweeps, G1, order-free (plan #5) ...
src/cachetest.loft|CACHE OK|/tmp/story_cache.log|field-cache|[cache] L2 region cache: cached == freshly derived (plan #5 P6) ...
src/feattest.loft|FEAT OK|/tmp/story_feat.log|features|[feat] doors + windows as surface intervals (plan #5 P5) ...
src/matrixtest.loft|MATRIX OK|/tmp/story_matrix.log|junction-matrix|[matrix] every shape pair through six invariants (plan #5 P4) ...
src/jointest.loft|JOIN OK|/tmp/story_join.log|junctions|[join] junction arbitration is order-independent (plan #5 P3) ...
src/matchtest.loft|MATCH OK|/tmp/story_match.log|matcher|[match] cells -> surfaces: cell-authored content gets normals (plan #5 P2) ...
src/waytest.loft|WAY OK|/tmp/story_way.log|ways|[ways] exact curves -> cells + edges + surface ids, one pass (plan #5 P1) ...
src/edgetest.loft|EDGE OK|/tmp/story_edge.log|edge-collision|[edge] wall collision as an EDGE cut — 1 edge blocks in all 24 headings (plan #5) ...
src/formtest.loft|FORM OK|/tmp/story_form.log|forms|[forms] hex->vector map vs the python golden (plan #5, exact integer contract) ...
src/meshtest.loft|MESH OK|/tmp/story_mesh.log|world-mesh|[mesh] world mesh: counts + exact R4 tint-bake colors (plan #7 P2) ...
src/replaytest.loft|REPLAY OK|/tmp/story_replay.log|replay|[replay] K2 replica invariant: intents + wire codec -> identical worlds ...
src/chunktest.loft|CHUNK OK|/tmp/story_chunk.log|chunk|[chunk] @PLN2 detail chunk: base+0.1m round-trip / watertight seam / 32x32 addressing ...
src/chunkgeotest.loft|CHUNKGEO OK|/tmp/story_chunkgeo.log|chunk-geo|[chunk-geo] @PLN2 S1 two-tier map: overworld hex + detail raster round-trips / tier sizes ...
src/chunkgentest.loft|CHUNKGEN OK|/tmp/story_chunkgen.log|chunk-gen|[chunk-gen] @PLN2 S2 overworld chunk from the engine: faithful sample + deterministic ...
src/detailtest.loft|DETAIL OK|/tmp/story_detail.log|detail|[detail] @PLN2 S3 detail LOD tier: round-trip / deterministic / watertight seam / LOD-consistent ...
src/meshchunktest.loft|MESHCHUNK OK|/tmp/story_meshchunk.log|mesh-chunk|[mesh-chunk] @PLN2 S4 chunk heightfield mesh: count / follows-data / watertight / deterministic ...
src/talustest.loft|TALUS OK|/tmp/story_talus.log|talus|[talus] @PLN2 S6.2 angle-of-repose talus on the detail tier: rubble conserved / repose / deterministic / faces+scree ...
EOF

# The games kernel (@PLN18 engine_host) lives in the sibling loft checkout — its
# natives ride the installed binary, the lib surface rides ../loft/lib. Skip (not
# fail) where the sibling is absent: the kernel dep is opt-in until registry-published.
if [ -d ../loft/lib/engine_host ]; then
  echo "  [kernel] engine_host consumable: natives + schema table (plan #6 K0) ..."
  # shellcheck disable=SC2086
  "$LOFT" --interpret $FLAGS --lib ../loft/lib/ src/kerneltest.loft | tee /tmp/story_kernel.log
  grep -q "KERNEL OK" /tmp/story_kernel.log || { echo "    FAIL: kernel"; exit 1; }
else
  echo "  [kernel] SKIP — ../loft/lib not present (sibling-checkout dep, plans/6-games-kernel/)"
fi

echo "  PASS"
