#!/usr/bin/env bash
# The headless deterministic test gate (extracted from the Makefile `test` target;
# `make test` delegates here). Same steps, same labels, same /tmp/story_*.log
# files — one table row per test, specials (kernel self-test, compile gate,
# bundle regeneration, the seam grep) written out where they sit in the order.
#
# Args: $1 = loft binary   $2 = loft flags (word-split: --path/--lib …)
#       $3 = kernel selftest .loft   $4 = game entry .loft
set -u
trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; printf '%s' "${s%"${s##*[![:space:]]}"}"; }
LOFT="$(trim "${1:?loft binary required}")"
FLAGS="${2-}"
KTEST="$(trim "${3:?kernel selftest .loft required}")"
SRC="$(trim "${4:?game entry .loft required}")"

# ── WHICH COMPILER PRODUCED THIS LOG ────────────────────────────────────────
#
# ⚠ `loft --version` IS NOT PROVENANCE. The installed binary reports "2026.8.0" while
# being ../loft's WORKING-TREE build, 15 commits past that tag and sometimes dirty —
# `loft verify-self` says "not a release bundle". It is rebuilt by another agent while
# our gates run: measured 2026-08-09, the binary changed mid-session and cdylibs were
# recompiled DURING a run, whose cargo output landed in this log.
#
# So the hash is the identity. Two logs with different md5 are NOT comparable, and a
# diff between them is not evidence about our code — which cost real time twice before
# this line existed (a warning that appeared once and never again; eight that arrived
# with no source change).
bin="$(command -v "$LOFT" 2>/dev/null || echo "$LOFT")"
echo "  [toolchain] $("$LOFT" --version 2>/dev/null | head -1) · md5 $(md5sum "$bin" 2>/dev/null | cut -c1-12) · $bin · built $(date -r "$bin" '+%Y-%m-%d %H:%M' 2>/dev/null)"
if [ -d ../loft/.git ]; then
  gd=$(git -C ../loft describe --tags --always --dirty 2>/dev/null)
  sib=$(md5sum ../loft/target/release/loft 2>/dev/null | cut -c1-12)
  if [ -n "$sib" ] && [ "$sib" = "$(md5sum "$bin" 2>/dev/null | cut -c1-12)" ]; then
    echo "              IS ../loft's working-tree build: ${gd:-?}  — not a release; provenance is that tree"
  else
    echo "              ../loft describe: ${gd:-?} (the installed binary is NOT that tree's build)"
  fi
fi

# ── QUIET ON PASS, LOUD ON FAIL, AND ALWAYS SAY WHERE THE TIME WENT ─────────
#
# ⚠ A GREEN TEST'S OUTPUT IS NOISE, AND THE NOISE HID THINGS. `tee`ing every test's
# stdout made a gate log ~100,000 lines, 98% of it compiler advice from runs that
# passed. Diffing two runs — the way a behaviour-preserving change is actually proved
# — meant filtering that by hand every time, and twice this month a real difference
# sat inside it unnoticed for an hour. loft's own Goal F is the rule: a tool that
# reports its good health teaches the reader to skip the line where it eventually
# reports the opposite.
#
# So a passing test prints ONE line, a failing one prints everything that matters,
# and the full output is still on disk per test (/tmp/story_<name>.log) — which is a
# BETTER diff target than the old combined stream, because it cannot interleave.
#
# ⚠ THE SECONDS ARE NOT DECORATION. A suite that takes minutes has to say where they
# went or nobody can shorten it: measured, six of 88 tests hold most of the wall time
# (quest 51s, travel 30s, replay 26s, surface 26s, sweep 22s, mesh 20s) and most of
# the rest are under two. That is only actionable if the gate prints it.
#
# GATE_VERBOSE=1 restores the old streaming behaviour for a single run.
GATE_T0=$(date +%s)
GATE_SLOW=$(mktemp)

# run <src-file> <ok-marker> <log> <fail-text> <label>
run() {
  t0=$(date +%s%N)
  if [ -n "${GATE_VERBOSE:-}" ]; then
    echo "  $5"
    # shellcheck disable=SC2086  # FLAGS must word-split into --path/--lib
    "$LOFT" --interpret $FLAGS "$1" | tee "$3"
  else
    # shellcheck disable=SC2086
    "$LOFT" --interpret $FLAGS "$1" > "$3" 2>&1
  fi
  ms=$(( ($(date +%s%N) - t0) / 1000000 ))
  name=$(basename "$1" .loft)
  printf '%s %s\n' "$ms" "$name" >> "$GATE_SLOW"
  if grep -q "$2" "$3"; then
    [ -n "${GATE_VERBOSE:-}" ] || printf '  ok %6d.%ds  %s\n' "$((ms / 1000))" "$(( (ms % 1000) / 100 ))" "$name"
  else
    # ⚠ A FAILURE PRINTS ITS EVIDENCE. The old form printed only "FAIL: <text>" and
    # left the reader to go find the log; the run had already scrolled past.
    printf '  FAIL %4d.%ds  %s — %s\n' "$((ms / 1000))" "$(( (ms % 1000) / 100 ))" "$name" "$4"
    echo "       ---- $3 (tail, compiler noise stripped) ----"
    grep -vE '^advice|^note:|^warning|^ *[0-9]+ \||^ *\||^ *-->|^ *\^|^$' "$3" | tail -12 | sed 's/^/       /'
    exit 1
  fi
}

# table <<EOF — file|marker|log|fail-text|label  (order = execution order)
table() {
  while IFS='|' read -r file marker log fail label; do
    [ -n "$file" ] || continue
    run "$file" "$marker" "$log" "$fail" "$label"
  done
}

# shellcheck disable=SC2086
if [ -n "${GATE_VERBOSE:-}" ]; then
  echo "  [1/14] kernel self-test (headless, deterministic) ..."
  "$LOFT" --interpret $FLAGS "$KTEST" | tee /tmp/story_selftest.log
else
  "$LOFT" --interpret $FLAGS "$KTEST" > /tmp/story_selftest.log 2>&1
fi
grep -q "ALL CHECKS PASS" /tmp/story_selftest.log || {
  echo "  FAIL  kernel self-test did not pass — /tmp/story_selftest.log"
  grep -vE '^advice|^note:|^warning|^ *[0-9]+ \||^ *\||^ *-->|^ *\^|^$' /tmp/story_selftest.log | tail -12 | sed 's/^/       /'
  exit 1; }

table <<'EOF'
src/combattest.loft|COMBAT OK|/tmp/story_combat.log|combat loop|[2/14] combat loop (player melee + enemy attacks) ...
src/wiretest.loft|WIRING OK|/tmp/story_wire.log|dungeon wiring|[3/14] dungeon wiring (procedural gen + DB monsters) ...
src/aitest.loft|AI OK|/tmp/story_ai.log|monster AI|[4/14] monster AI (awareness + never-move) ...
src/placetest.loft|PLACEMENT OK|/tmp/story_place.log|placement|[5/14] placement (budget + weighted + start-safe) ...
src/leveltest.loft|LEVEL OK|/tmp/story_level.log|levels|[6/14] levels (stairs + descent) ...
src/herotest.loft|HERO OK|/tmp/story_hero.log|hero|[7/14] hero (XP + level-up) ...
src/curvetest.loft|CURVE OK|/tmp/story_curve.log|curve|[8/14] curve + ratio cap (gentle, fair, capped) ...
src/itemtest.loft|ITEM OK|/tmp/story_item.log|items|[9/14] items (gold + drops + pickup) ...
src/equiptest.loft|EQUIP OK|/tmp/story_equip.log|equipment|[10/14] equipment (wield + effects) ...
src/savetest.loft|SAVE OK|/tmp/story_save.log|save points|[11/14] save points (checkpoint respawn + grave) ...
src/fovtest.loft|FOV OK|/tmp/story_fov.log|FOV|[12/14] FOV (facing-cone fog-of-war) ...
src/sprite_drawtest.loft|SPRITE OK|/tmp/story_sprite.log|sprite rasterizer|[13/14] sprite rasterizer (fill_polygon scanline) ...
EOF

echo "  [14/14] compile gate (parse + bytecode) ..."
# shellcheck disable=SC2086
"$LOFT" --interpret --check $FLAGS "$SRC" >/dev/null 2>&1 || {
  echo "    FAIL: compile"; exit 1; }

echo "  [bundles] regenerate index + character-bundle test ..."
"$LOFT" --interpret src/genbundles.loft >/dev/null 2>&1
run src/bundletest.loft "BUNDLE OK" /tmp/story_bundle.log "bundles" \
  "[bundles] character-bundle test ..."

table <<'EOF'
src/bundledeftest.loft|BUNDLEDEF OK|/tmp/story_bundledef.log|bundle-defs|[bundle-defs] world bundle enemies/items -> catalog merge ...
src/deftest.loft|DEFS OK|/tmp/story_defs.log|defs|[defs] class/race/item tables — races now per-bundle via race_catalog ...
src/producttest.loft|PRODUCT OK|/tmp/story_product.log|production|[production] I-PROD: engine repertoire then bundles', indexed modulo the total (BUNDLE.md) ...
src/roomtest.loft|ROOMS OK|/tmp/story_rooms.log|rooms|[rooms] rooms bundle -> room registry ...
src/itemusetest.loft|ITEM-USE OK|/tmp/story_itemuse.log|item-use|[items] item-use (Explorer potions: heal + custom detect) ...
src/clocktest.loft|CLOCK OK|/tmp/story_clock.log|clock|[clock] monster energy/speed (1.0x vs 1.5x) ...
src/statustest.loft|STATUS OK|/tmp/story_status.log|status|[status] timed statuses (slow / stun, pre-calc expiry) ...
src/persisttest.loft|PERSIST OK|/tmp/story_persist.log|persist|[persist] dungeon delta round-trip (death-only; regenerate + replay) ...
src/surfacetest.loft|SURFACE OK|/tmp/story_surface.log|surface|[surface] depth-0 desert + dungeon entrance (SLICE step 1+2) ...
src/skilltest.loft|SKILL OK|/tmp/story_skill.log|skill|[skills] passive melee skill (level + STR -> damage) ...
src/depthtest.loft|DEPTH OK|/tmp/story_depth.log|depth|[depth] beginner-dungeon spawn pool is depth-gentle (no lich at 1-3) ...
src/rangedtest.loft|RANGED OK|/tmp/story_ranged.log|ranged|[ranged] launcher fire action (bow + ammo -> shoot) ...
src/quickslottest.loft|QUICKSLOT OK|/tmp/story_quickslot.log|quickslot|[quickslot] type-routed auto-slot + bind + press-to-use dispatch ...
src/questtest.loft|QUEST OK|/tmp/story_quest.log|quest|[quest] desert_surprise overlay: throne set-piece + grant + boss -> infestation ...
src/msgtest.loft|MSG OK|/tmp/story_msg.log|msg|[msg] message log: ring buffer + event lines (kill/level/descend/nothing) ...
src/invhubtest.loft|INVHUB OK|/tmp/story_invhub.log|invhub|[invhub] inventory hub: two ring slots + equipped names + reslot bind ...
src/effecttest.loft|EFFECT OK|/tmp/story_effect.log|effect|[effect] use-item effects: blink / heal / restore / magic-mapping ...
src/specialtest.loft|SPECIAL OK|/tmp/story_special.log|special|[special] monster specials: gaze paralysis + venom + antivenin ward (+ deadlock/struggle) ...
src/unknowntest.loft|UNKNOWN OK|/tmp/story_unknown.log|unknown|[unknown] unknown items: per-game flavours / identify-on-use / carry / IF_KNOWN exempt ...
src/racetest.loft|RACE OK|/tmp/story_race.log|race|[race] chosen race applies: stat block / hit-die HP / skills / save / free-action gate ...
src/classtest.loft|CLASS OK|/tmp/story_class.log|class|[class] classes from bundles: apply / SP pool / the spell chain (routine-by-id) ...
src/crystaltest.loft|CRYSTAL OK|/tmp/story_crystal.log|crystal|[crystal] the shrine re-spec: bump = interact / apply race+class / roster ...
src/overlandtest.loft|OVERLAND OK|/tmp/story_overland.log|overland|[overland] the contract wilderness: invariants / walked scale / towns+roads ...
src/cavetest.loft|CAVE OK|/tmp/story_cave.log|cave|[cave] natural caves: mouths on the surface, narrow winding levels ...
EOF

echo "  [seam] trait seam: no engine spawn by monster key (plan #4 A) ..."
if grep -n 'mon_find("' src/*.loft | grep -v spawn_crystal | grep -q .; then
  echo "    FAIL: engine references a monster key:"
  grep -n 'mon_find("' src/*.loft | grep -v spawn_crystal
  exit 1
fi

# The library seam, next to the bundle one: no forked module, no shadowed name, no second
# resolution path (ADOPTION.md P4). Reads committed files only — no toolchain, ~1 s.
echo "  [libs] library seam: lock complete, no --lib shadowing, no forked module (ADOPTION.md P4) ..."
python3 tools/libcheck.py || exit 1

table <<'EOF'
src/traveltest.loft|TRAVEL OK|/tmp/story_travel.log|travel|[travel] window crossing + the desert gate ...
src/idletest.loft|IDLESKIP OK|/tmp/story_idle.log|idle-skip|[idle-skip] scene key: hold when idle, bump on events (plan #7 P1) ...
src/pointstest.loft|POINTS OK|/tmp/story_points.log|railway-points|[points] turnout + reverse curve: 15-deg sweeps, G1, order-free (plan #5) ...
src/crossingtest.loft|CROSSING OK|/tmp/story_crossing.log|crossings|[cross] diamonds + double slips: R_max bound, slip invisible in cells (plan #5) ...
src/levelxtest.loft|LEVELX OK|/tmp/story_levelx.log|level-crossings|[levelx] road x rail at grade; barrier toggle keeps the L2 cache (plan #5) ...
src/platformtest.loft|PLATFORM OK|/tmp/story_platform.log|platforms|[plat] concentric platform exact, chord costs L^2/8R (plan #5) ...
src/sighttest.loft|SIGHT OK|/tmp/story_sight.log|signal-sighting|[sight] opacity-not-solidity, height, curve cutback D^2/8R (plan #5) ...
src/bridgetest.loft|BRIDGE OK|/tmp/story_bridge.log|bridges-tunnels|[bridge] levels: same ways, crossing vs bridge; bore leaves no mark (plan #5) ...
src/stairtest.loft|STAIR OK|/tmp/story_stair.log|stairs|[stair] per-cell height; min tread = sqrt(3)*max|cos|; nosing = sight line (plan #5) ...
src/spiraltest.loft|SPIRAL OK|/tmp/story_spiral.log|spiral-stairs|[spiral] sector treads; inner going is the bound; small spiral is sub-grid (plan #5) ...
src/rooftest.loft|ROOF OK|/tmp/story_roof.log|roofs-arches|[roof] one distance mechanism; cone eave; arch clear height (plan #5) ...
src/roofmatchtest.loft|ROOFMATCH OK|/tmp/story_roofmatch.log|roof-matching|[rmatch] recover the cone; planar roofs just interpolate (plan #5) ...
src/vaulttest.loft|VAULT OK|/tmp/story_vault.log|domes-vaults|[vault] dome slope ceiling; groin vs cloister is one operator (plan #5) ...
src/canopytest.loft|CANOPY OK|/tmp/story_canopy.log|canopy-partition|[canopy] exact-integer argmax; contested cells to the biggest tree (plan #9 T1) ...
src/canopyvoltest.loft|CANOPYVOL OK|/tmp/story_canopyvol.log|canopy-volume|[canopyvol] canopy interval; crowding raises the bole (plan #9 T2) ...
src/canopyleantest.loft|CANOPYLEAN OK|/tmp/story_canopylean.log|canopy-lean|[canopylean] lean bound is a theorem; Case B signs (plan #9 T3) ...
src/canopyskeltest.loft|CANOPYSKEL OK|/tmp/story_canopyskel.log|canopy-skeleton|[canopyskel] shortest-path skeleton; I-REACH/I-NOTRESPASS controls (plan #9 T4) ...
src/canopypipetest.loft|CANOPYPIPE OK|/tmp/story_canopypipe.log|canopy-pipe|[canopypipe] r = k*sqrt(load); da Vinci is the pipe model (plan #9 T5) ...
src/canopyrelaxtest.loft|CANOPYRELAX OK|/tmp/story_canopyrelax.log|canopy-relax|[canopyrelax] termination detected, not assumed; exclusion emerges (plan #9 T6) ...
src/canopylighttest.loft|CANOPYLIGHT OK|/tmp/story_canopylight.log|canopy-light|[canopylight] volumetric sky fraction; gap regeneration; levels (plan #9 T7) ...
src/scaletest.loft|SCALE OK|/tmp/story_scale.log|scale-contract|[scale] one grid, two readings; every threshold checked in metres ...
src/primtest.loft|PRIM OK|/tmp/story_prim.log|axis-primitives|[prim] drums about any axis; a wheel is a tower on its side (plan #10 P1) ...
src/proptest.loft|PART OK|/tmp/story_part.log|part-lists|[part] a cart is six parts and two mechanisms (plan #10 P2) ...
src/seattest.loft|SEAT OK|/tmp/story_seat.log|seated-props|[seat] chimney cut on the pitch, posts plumb, pipe length derived (plan #10 P3) ...
src/proplevtest.loft|PROPLEV OK|/tmp/story_proplev.log|prop-level|[proplev] props on their own sheet; a cart cannot alter a gate (plan #10 P4) ...
src/propgentest.loft|PROPGEN OK|/tmp/story_propgen.log|derived-props|[propgen] a village furnishes itself: one door per opening (plan #10 P5) ...
src/hingetest.loft|HINGE OK|/tmp/story_hinge.log|hinged-state|[hinge] one number swings the leaf and sets the material (plan #10 P6) ...
src/wheeltest.loft|WHEEL OK|/tmp/story_wheel.log|wheel-state|[wheel] no-slip: the arc turned equals the ground covered (plan #10 P7) ...
src/linktest.loft|LINK OK|/tmp/story_link.log|linkage-state|[link] the con-rod does not stretch, over 360 crank angles (plan #10 P8) ...
src/canopyfloortest.loft|CANOPYFLOOR OK|/tmp/story_canopyfloor.log|canopy-floor|[canopyfloor] field vs object at R = 2*sqrt(3), by fork test (plan #9 T8) ...
src/canopycardtest.loft|CANOPYCARD OK|/tmp/story_canopycard.log|canopy-cards|[canopycard] branch-aligned cards; the heading fix was the basis (plan #9 T9) ...
src/canopyopactest.loft|CANOPYOPAC OK|/tmp/story_canopyopac.log|canopy-opacity|[canopyopac] I-OPACITY: drawn density == simulated density (plan #9 T10) ...
src/canopytest.loft|CANOPY OK|/tmp/story_canopy.log|canopy-partition|[canopy] exact-integer argmax partition; symmetric pair (plan #9 T1) ...
src/cachetest.loft|CACHE OK|/tmp/story_cache.log|field-cache|[cache] L2 region cache: cached == freshly derived (plan #5 P6) ...
src/feattest.loft|FEAT OK|/tmp/story_feat.log|features|[feat] doors + windows as surface intervals (plan #5 P5) ...
src/matrixtest.loft|MATRIX OK|/tmp/story_matrix.log|junction-matrix|[matrix] every shape pair through six invariants (plan #5 P4) ...
src/jointest.loft|JOIN OK|/tmp/story_join.log|junctions|[join] junction arbitration is order-independent (plan #5 P3) ...
src/matchtest.loft|MATCH OK|/tmp/story_match.log|matcher|[match] cells -> surfaces: cell-authored content gets normals (plan #5 P2) ...
src/waytest.loft|WAY OK|/tmp/story_way.log|ways|[ways] exact curves -> cells + edges + surface ids, one pass (plan #5 P1) ...
src/edgetest.loft|EDGE OK|/tmp/story_edge.log|edge-collision|[edge] wall collision as an EDGE cut — 1 edge blocks in all 24 headings (plan #5) ...
src/fieldtest.loft|FIELD OK|/tmp/story_field.log|field-differential|[field] plan #11 P2: old passability model == new, every hex and direction ...
src/sweeptest.loft|SWEEP OK|/tmp/story_sweep.log|swept-movement|[sweep] plan #11 P2b: a PATH crosses walls, not a probe point — same walls at any dt ...
src/scenetest.loft|SCENE OK|/tmp/story_scene.log|camera|[scene] plan #11 P3: hex -> pixel -> the same hex; metric parity (I-STAND) ...
src/formtest.loft|FORM OK|/tmp/story_form.log|forms|[forms] hex->vector map vs the python golden (plan #5, exact integer contract) ...
src/meshtest.loft|MESH OK|/tmp/story_mesh.log|world-mesh|[mesh] world mesh: counts + exact R4 tint-bake colors (plan #7 P2) ...
src/replaytest.loft|REPLAY OK|/tmp/story_replay.log|replay|[replay] K2 replica invariant: intents + wire codec -> identical worlds ...
src/chunktest.loft|CHUNK OK|/tmp/story_chunk.log|chunk|[chunk] @PLN2 detail chunk: base+0.1m round-trip / watertight seam / 32x32 addressing ...
src/chunkgeotest.loft|CHUNKGEO OK|/tmp/story_chunkgeo.log|chunk-geo|[chunk-geo] @PLN2 S1 two-tier map: overworld hex + detail raster round-trips / tier sizes ...
src/chunkgentest.loft|CHUNKGEN OK|/tmp/story_chunkgen.log|chunk-gen|[chunk-gen] @PLN2 S2 overworld chunk from the engine: faithful sample + deterministic ...
src/detailtest.loft|DETAIL OK|/tmp/story_detail.log|detail|[detail] @PLN2 S3 detail LOD tier: round-trip / deterministic / watertight seam / LOD-consistent ...
src/meshchunktest.loft|MESHCHUNK OK|/tmp/story_meshchunk.log|mesh-chunk|[mesh-chunk] @PLN2 S4 chunk heightfield mesh: count / follows-data / watertight / deterministic ...
src/talustest.loft|TALUS OK|/tmp/story_talus.log|talus|[talus] @PLN2 S6.2 angle-of-repose talus on the detail tier: rubble conserved / repose / deterministic / faces+scree ...
EOF

# The games kernel (@PLN18 engine_host) lives in the sibling loft checkout — its
# natives ride the installed binary, the lib surface rides ../loft/lib. Skip (not
# fail) where the sibling is absent: the kernel dep is opt-in until registry-published.
if [ -d ../loft/lib/engine_host ]; then
  echo "  [kernel] engine_host consumable: natives + schema table (plan #6 K0) ..."
  # shellcheck disable=SC2086
  if [ -n "${GATE_VERBOSE:-}" ]; then
    "$LOFT" --interpret $FLAGS --lib ../loft/lib/ src/kerneltest.loft | tee /tmp/story_kernel.log
  else
    "$LOFT" --interpret $FLAGS --lib ../loft/lib/ src/kerneltest.loft > /tmp/story_kernel.log 2>&1
  fi
  grep -q "KERNEL OK" /tmp/story_kernel.log || {
    echo "  FAIL  kernel (engine_host) — /tmp/story_kernel.log"
    grep -vE '^advice|^note:|^warning|^ *[0-9]+ \||^ *\||^ *-->|^ *\^|^$' /tmp/story_kernel.log | tail -12 | sed 's/^/       /'
    exit 1; }
else
  echo "  [kernel] SKIP — ../loft/lib not present (sibling-checkout dep, plans/6-games-kernel/)"
fi

# ── WHERE THE MINUTES WENT ──────────────────────────────────────────────────
# Printed on the way out, so shortening the gate is a decision anyone can make from
# its own output rather than from a profiling session nobody runs. The threshold is
# absolute (5 s) rather than a top-N: a top-N always prints something and so says
# nothing, while a fixed bar goes SILENT once the suite is uniformly fast, which is
# the state we want it to be able to report.
if [ -s "$GATE_SLOW" ]; then
  slow=$(sort -rn "$GATE_SLOW" | awk '$1 >= 5000 {printf "%s %d.%ds", sep, $1/1000, ($1%1000)/100; sep=" ·"} {}' \
         | sed 's/^ *//')
  total=$(( $(date +%s) - GATE_T0 ))
  n=$(wc -l < "$GATE_SLOW")
  if [ -n "$slow" ]; then
    printf '  %d tests in %dm%02ds · over 5s: %s\n' "$n" "$((total / 60))" "$((total % 60))" \
      "$(sort -rn "$GATE_SLOW" | awk '$1 >= 5000 {printf "%s%s %d.%ds", sep, $2, $1/1000, ($1%1000)/100; sep=" · "}')"
  else
    printf '  %d tests in %dm%02ds · none over 5s\n' "$n" "$((total / 60))" "$((total % 60))"
  fi
fi
rm -f "$GATE_SLOW"

echo "  PASS"
